apiVersion: batch/v1
kind: Job
metadata:
  name: sleepjob
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
      - image: busybox:latest
        name: sleepjob
        command: ["/bin/sh", "-c" ,"sleep 10"]
        resources: {}
      restartPolicy: Never
