apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: crawlmanager
    docker:
      dockerfile: infrastructure/dockerfile-crawlmanager
  - image: crawljob
    docker:
      dockerfile: infrastructure/dockerfile-job
deploy:
  helm:
    releases:
    - name: sitemapper
      chartPath: helm/sitemapper
      artifactOverrides:
        crawlmanager.image: crawlmanager
        crawlJob.image: crawljob
      imageStrategy:
        helm: {}
