apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitemapper-api
  labels:
    {{- include "sitemapper.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: sitemapper-api
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: sitemapper-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sitemapper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: api-port
              containerPort: {{ .Values.api.port }}
          livenessProbe:
            periodSeconds: 30
            httpGet:
              path: /live
              port: api-port
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            httpGet:
              path: /ready
              port: api-port
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ASTRA_CLIENT_ZIP_PATH
              valueFrom:
                secretKeyRef:
                  key: zipPath
                  name: astra-auth
            - name: ASTRA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: astra-auth
                  key: clientSecret
            - name: ASTRA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: astra-auth
                  key: clientID
          envFrom:
            - configMapRef:
                name: sitemapper
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
