apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawlmanager
  labels:
    {{- include "sitemapper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sitemapper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sitemapper.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sitemapper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: crawlmanager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.crawlmanager.image.repository }}:{{ .Values.crawlmanager.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.crawlmanager.image.pullPolicy }}
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
          readinessProbe:
            exec:
              command:
                - stat
                - /ready/ready.txt
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ASTRA_CLIENT_ZIP_PATH
              valueFrom:
                secretKeyRef:
                  key: zipPath
                  name: astra-auth
            - name: ASTRA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: astra-auth
                  key: clientSecret
            - name: ASTRA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: astra-auth
                  key: clientID
          envFrom:
            - configMapRef:
                name: sitemapper
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
