apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitemapper.fullname" . }}
  labels:
    {{- include "sitemapper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api-port
      protocol: TCP
  selector:
    app: sitemapper-api
