apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sitemapper.fullname" . }}
  labels:
    {{- include "sitemapper.labels" . | nindent 4 }}
data:
  NAMESPACE: {{ .Release.Namespace | quote }}
  JOB_TTL: "10"
  JOB_IMAGE: "{{ .Values.crawlJob.image.repository }}:{{ .Values.crawlJob.image.tag | default .Chart.AppVersion }}"
  NATS_SERVER: {{ .Values.nats.server | quote }}
  NATS_RESULTS_SUBJECT: {{ .Values.nats.resultsSubject | quote }}
  NATS_CRAWL_SUBJECT: {{ .Values.nats.crawlSubject | quote }}
