apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sitemapper.fullname" . }}
  labels:
    {{- include "sitemapper.labels" . | nindent 4 }}
data:
  NATS_SERVER: {{ .Values.nats.server | quote }}
  NATS_RESULTS_SUBJECT: {{ .Values.nats.resultsSubject | quote }}
