ARG GO_VERSION=1.17.2

# STAGE 1: building the executable
FROM golang:${GO_VERSION}-alpine AS build
RUN apk add --no-cache git
RUN apk --no-cache add ca-certificates



WORKDIR /src
COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./sitemapper ./sitemapper

# Build the executable
RUN CGO_ENABLED=0 go build -v -o /api ./sitemapper/cmd/api

# STAGE 2: build the container to run
FROM alpine AS final
LABEL maintainer="dinofizz"

RUN mkdir /ready

COPY --from=build /api /api
COPY ./secure-connect-sitemapper.zip /astra/secure-connect-sitemapper.zip
# copy ca certs
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

RUN addgroup -S  api \
    && adduser -S -u 10000 -g api api

RUN chown -R api:api /ready
USER api

ENTRYPOINT ["/api"]
