ARG GO_VERSION=1.17.2

# STAGE 1: building the executable
FROM golang:${GO_VERSION}-alpine AS build
RUN apk add --no-cache git
RUN apk --no-cache add ca-certificates



WORKDIR /src
COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./crawlmanager ./crawlmanager

# Build the executable
RUN CGO_ENABLED=0 go build -v -o /cm ./crawlmanager

# STAGE 2: build the container to run
FROM alpine AS final
LABEL maintainer="dinofizz"

RUN mkdir /ready

COPY --from=build /cm /crawlmanager

# copy ca certs
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# add a user here because addgroup and adduser are not available in scratch
RUN addgroup -S crawlmanager \
    && adduser -S -u 10000 -g crawlmanager crawlmanager

RUN chown -R crawlmanager:crawlmanager /ready
USER crawlmanager

ENTRYPOINT ["/crawlmanager"]
