ARG GO_VERSION=1.17.2

# STAGE 1: building the executable
FROM golang:${GO_VERSION}-alpine AS build
RUN apk add --no-cache git
RUN apk --no-cache add ca-certificates

# add a user here because addgroup and adduser are not available in scratch
RUN addgroup -S sitemapperuser \
    && adduser -S -u 10000 -g sitemapperuser sitemapperuser

WORKDIR /src
COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./sitemapper ./sitemapper

# Build the executable
RUN CGO_ENABLED=0 go build -v -o /sitemapper ./sitemapper/cmd/job

# STAGE 2: build the container to run
FROM scratch AS final
LABEL maintainer="dinofizz"
COPY --from=build /sitemapper /sitemapper

# copy ca certs
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# copy users from builder (use from=0 for illustration purposes)
COPY --from=0 /etc/passwd /etc/passwd

USER sitemapperuser

ENTRYPOINT ["/sitemapper"]
